[package]
name = "bevy_editor_pls"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
edition = "2018"

[features]
default = ["bevy/dynamic"]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", branch = "main", default-features = false, features = ["render"] }
bevy-inspector-egui = { git = "https://github.com/jakobhellermann/bevy-inspector-egui", branch = "bevy-0.5" }
bevy_mod_picking = { git = "https://github.com/jakobhellermann/bevy_mod_picking" }
bevy_fly_camera = { git = "https://github.com/jakobhellermann/bevy_fly_camera" }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", branch = "main", default-features = false, features = ["bevy_wgpu", "x11"] }
