[package]
name = "bevy_editor_pls_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.6", default-features = false }
bevy_egui = "0.10"
bevy-inspector-egui = "0.7"
indexmap = "1.7"