[package]
name = "bevy_editor_pls"
version = "0.1.0"
edition = "2021"

[features]
default_windows = ["bevy_editor_pls_default_windows", "bevy/bevy_render", "bevy/bevy_pbr"]
default = ["default_windows"]

[dependencies]
bevy = { version = "0.6", default-features = false }
bevy_editor_pls_core = { path = "../bevy_editor_pls_core" }
bevy_editor_pls_default_windows = { path = "../bevy_editor_pls_default_windows", optional = true }