[package]
name = "bevy_editor_pls_default_windows"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_editor_pls_core = { path = "../bevy_editor_pls_core" }
bevy-inspector-egui = { git = "https://github.com/jakobhellermann/bevy-inspector-egui", branch = "bevy-main" }