[package]
name = "basic"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_editor_pls = { path = "../../crates/bevy_editor_pls" }
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false, features = [
    "bevy_winit",
    "x11",
] }
